name: Monitor Blockchain Events

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install Node packages
      run: pnpm install

    - name: Run event monitoring script
      env:
          DISCORD_WEBHOOK: ${{ github.ref == 'refs/heads/main' && secrets.DISCORD_WEBHOOK || '' }}
          RPC_URL: ${{ secrets.RPC_URL }}
          NODE_ADDRESS: ${{ vars.NODE_ADDRESS }}
          MIN_BALANCE: ${{ vars.MIN_BALANCE }}
          BATCH_BLOCK: 490
      run: |
        pnpm run monitor

    - name: Run canSettle monitoring script
      env:
          DISCORD_WEBHOOK: ${{ github.ref == 'refs/heads/main' && secrets.DISCORD_WEBHOOK || '' }}
          RPC_URL: ${{ secrets.RPC_URL }}
          DAVE_CONTRACT_ADDRESS: ${{ vars.DAVE_CONSENSUS_ADDRESS }}
      run: |
        pnpm run can-settle-monitor

    - name: Commit and push data
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add data
        git diff --cached --quiet || git commit -m "Run monitor job"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
